# -*- coding: utf-8 -*-
"""Part2-FundamentalDE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14_trK9CsGtvEdC332o2-vTr4CpGyDF9I

FUNDAMENTAL OF DE - PART 2

TASK 1

1. Kapan kita harus menggunakan relational database atau nosql database?

Kita harus menggunakan relational database jika data yang kita gunakan:
- Memiliki struktur data yang tetap (structured data).
- Membutuhkan konsistensi yang tinggi, yaitu ACID (Atomicity, Consistency, Isolation, Durability) adalah empat prinsip dalam manajemen basis data (database).
- Memerlukan kueri kompleks yang melibatkan join antara beberapa tabel.

Kita harus menggunakan NoSQL database jika data yang kita gunakan:
- Memiliki data semi-structured atau unstructured.
- Memerlukan skalabilitas horizontal untuk menangani volume data yang besar karena NoSQL dapat memberikan fleksibilitas dalam menambahkan node.
- Membutuhkan kinerja yang sangat tinggi.
- Memerlukan fleksibilitas schema karena NoSQL dapat memberikan fleksibilitas untuk mengubah skema data tanpa perlu menghentikan atau mengubah struktur database.
- Memerlukan pengelolaan data yang mudah tanpa menggunakan kompleksitas pengelolaan basis data yang relatif tinggi dari relational database.

2. Apa perbedaan antara database, data lake, data warehouse, dan data mart?

- Database adalah kumpulan data yang terorganisir secara terstruktur untuk menyimpan, mengelola, dan mengakses data. Contoh: PostgreSQL, MySQL, Oracle.
- Data lake adalah penyimpanan data yang memungkinkan kita menyimpan data mentah dalam berbagai format tanpa mengubahnya dan mengabaikan ukuran data dimana struktur data bisa berupa semi-terstruktur maupun unstructured. Contoh: Apache Hadoop, Amazon S3, Google CLoud Storage.
- Data warehouse adalah penyimpanan data yang dirancang untuk analisis data terstruktur maupun semi-terstruktur dan pelaporan bisnis dalam suatu tempat yang berasal dari berbagai sumber data. Contoh: Amazon Redshift, Google BigQuery, Snowflake.
- Data mart adalah subset dari data warehouse yang berfokus pada satu area fungsional atau unit bisnis dimana memiliki struktur data berupa skema bintang atau snowflake yang sama dengan data warehouse. Contoh: Finance data mart, Sales data mart, HR data mart.

3. Jelaskan apa itu normalisasi database dan normalisasikan tabel di bawah ini.

Normalisasi database adalah proses desain database yang dilakukan untuk mengorganisir struktur tabel agar sesuai dengan prinsip-prinsip normalisasi yang bertujuan untuk mengurangi redudansi data dan memastikan dependensi data yang konsisten, sehingga menghasilkan desain database yang lebih efisien, fleksibel, dan mudah dipelihara.

Hasil normalisasi data dari soal (lihat gambar di luar berkas ini)
"""